### numpy


In [2]:
import numpy as np 

a=[1,2,3,4,5,6]
arr1=np.array(a)
print(arr1.reshape(1,6))
print(arr1.reshape(2,3))
print(arr1.reshape(3,2))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [3]:
b=[[1,2,3],
   [4,5,6],
   [7,8,9]]
arr2=np.array(b)
print(arr2.reshape(3,3))
print(arr2.reshape(3,3,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
